-- INSTRUÇÕES PARA CONFIGURAÇÃO DO SUPABASE
-- Copie este código e execute no "SQL Editor" do seu painel Supabase.

-- 1. Criar Tabela de Perfis
CREATE TABLE IF NOT EXISTS profiles (
  id UUID PRIMARY KEY,
  name TEXT,
  email TEXT,
  avatar TEXT,
  role TEXT,
  company TEXT,
  department TEXT,
  registration_number TEXT,
  cpf TEXT,
  matricula TEXT,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Criar Tabela de Configurações
CREATE TABLE IF NOT EXISTS settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL,
  notifications BOOLEAN DEFAULT TRUE,
  notification_prefs JSONB,
  theme TEXT DEFAULT 'system',
  color_palette TEXT DEFAULT 'default',
  vacation_mode JSONB,
  workload JSONB,
  tolerance INTEGER DEFAULT 10,
  night_shift JSONB,
  bank_of_hours JSONB,
  total_balance_view TEXT DEFAULT 'week',
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(user_id)
);

-- 3. Criar Tabela de Registros (Logs)
CREATE TABLE IF NOT EXISTS logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL,
  timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
  type TEXT NOT NULL,
  observations TEXT,
  ticket_image TEXT,
  location TEXT,
  coords JSONB,
  nsr TEXT,
  worked_ms BIGINT,
  note TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Criar Tabela de Escalas Customizadas
CREATE TABLE IF NOT EXISTS custom_shifts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL,
  date_key TEXT NOT NULL,
  shift JSONB,
  is_off BOOLEAN DEFAULT FALSE,
  is_holiday BOOLEAN DEFAULT FALSE,
  is_vacation BOOLEAN DEFAULT FALSE,
  is_medical BOOLEAN DEFAULT FALSE,
  is_training BOOLEAN DEFAULT FALSE,
  is_absence BOOLEAN DEFAULT FALSE,
  is_manual_adjustment BOOLEAN DEFAULT FALSE,
  is_different_workload BOOLEAN DEFAULT FALSE,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(user_id, date_key)
);

-- 5. Criar Tabela de Atestados Médicos
CREATE TABLE IF NOT EXISTS medical_certificates (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  date DATE NOT NULL,
  is_full_day BOOLEAN DEFAULT TRUE,
  start_time TEXT,
  end_time TEXT,
  image TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 6. Desativar RLS (Segurança de Nível de Linha) para simplificar
ALTER TABLE logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE settings DISABLE ROW LEVEL SECURITY;
ALTER TABLE custom_shifts DISABLE ROW LEVEL SECURITY;
ALTER TABLE medical_certificates DISABLE ROW LEVEL SECURITY;

-- 7. Configuração de Storage (Buckets)
-- Importante: Crie o bucket "tickets" manualmente no painel Supabase como "Public".
-- Se quiser usar políticas de segurança para o Storage, execute os comandos abaixo:

-- Permitir que qualquer pessoa leia arquivos no bucket "tickets" (se for público)
-- CREATE POLICY "Acesso Público" ON storage.objects FOR SELECT USING (bucket_id = 'tickets');

-- Permitir que usuários autenticados (ou anônimos se RLS desativado) façam upload
-- CREATE POLICY "Upload Livre" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'tickets');
